version: "3"
services:
  jira:
    image: "atlassian/jira-software:${JIRA_VERSION}"
    container_name: jira
    ports:
      - "8080:8080"
    environment:
      - JVM_SUPPORT_RECOMMENDED_ARGS=-Datlassian.plugins.enable.wait=300
    volumes:
      - ./Atlassian.Jira.Test.Integration.Setup/import/:/var/atlassian/application-data/jira/import/